[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 5
replicas = 1

[[services]]
name = "api"
type = "web"
command = "web"
minReplicas = 1
maxReplicas = 2

[[services]]
name = "celery-worker"
type = "worker"
command = "worker"
replicas = 1

[[services]]
name = "celery-beat"
type = "worker"
command = "beat"
replicas = 1
